### PR TITLE
Implement clear parameter value

### PR DESCRIPTION
**Pull request by Splaxi**
To support the scenario where you want to be 100% sure that you don't leak sensitive / semi-sensitive data from your development.

Will simply assign an empty "[]" json property value to the defaultvalue.

Contains:
1 x Unit test to test that it works like expected

1 x modification of existing unit test, to validate that the change didn't break anything.

### CODE REVIEW

**Comment by Splaxi** [comment]
My initial testing found that [] worked better.

If you want, I can see if I can do some more testing with the other values...

**Comment by MLogdberg** [comment]
Then we go for []. Thanks for testing it out

**Comment by Splaxi** [comment]
And if we get some bug reports, then we know where to look 😉

**Comment by MLogdberg** [comment]
True!

Med vänlig hälsning,
Mattias

Skickat från min iPhone

9 aug. 2019 kl. 20:13 skrev Mötz Jensen <notifications@github.com<mailto:notifications@github.com>>:


And if we get some bug reports, then we know where to look 😉

**Pull request merged**
