### PR TITLE
Including Get-RGLogicAppsTemplate powershell script.

### PR DESCRIPTION
**Pull request by wsilveiranz**
This script allow a user to point to a resource group and generate templates for each logic app within that resource group.

### CODE REVIEW

**Comment by MLogdberg** [comment]
Nice, but could you add an example of usage to the Readme.md page as part of the PR?

**Comment by wsilveiranz** [comment]
No probs.

Will do and update the PR. Newbie on this whole Git contributor thingie... ;-D

Cheers, Wagner.

Wagner Silveira | Principal Consultant | Theta
Microsoft Azure MVP | MCSA - Cloud Platform m | P-TSP - Integration
D. +64 9 924 0105 | M. +64 21 560 363
wagner.silveira@theta.co.nz

**Comment by wsilveiranz** [comment]
README.md created in the cmdlet folder. Let me know if that is what you were expecting.

**Comment by MLogdberg** [comment]
Great! I'll add this, next would be to also add link from first page readme so that other easier find/understand that there is a complete script ready to help them export all Logic Apps..

**Pull request merged**
